import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Sidebar from '@/components/Sidebar'
import Rightbar from '@/components/Rightbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <div className="components">
            <div className="sidebar-page">
              <Sidebar/>
            </div>
            <div className="main-page">
            {children}
            </div>
            <div className="follow-page">
              <Rightbar/>
            </div>
          </div>
          </div></body>
    </html>
  )
}